# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.0

# mod
mod_id=eaglemixins
mod_name=EagleMixins
mod_version=1.2.4
mod_author=["NLBlackEagle"]
mod_description=Mixins for RLCraft Dregora
mixin_loader_class=eaglemixins.EagleMixinsPlugin

# dependencies
srparasites_version=1.12.2v1.9.21
opencomputers_version=MC1.12.2-1.8.9a+8ca336f
simpledifficulty_version=360779:3613814
fermiumbooter_version=968474:7279112
rlartifacts_version=819886:4475428
first_aid_version=276837:4414252
fishsundeadrising_version=321139:5107583
legendarytooltips_version=532127:5734973
sereneseasons_version=291874:2799213
dynamictrees_version=252818:3812473
charm_version=318872:3146596
champions_version=307152:3177947
otg_version=265894:7004304
bop_version=220318:3558882
loadingscreens_version=319264:2698971
sme_version=267035:6933862
bettersurvival_version=260360:5729552
reskillable_version=286382:2815686
rlcombat_version=711714:5940474
enhancedvisuals_version=255389:3507523
creativecore_version=257814:4722163
nuclearcraft_version=226254:6151363
cooking_for_blockheads_version=231484:2862651
quark_version=243121:2924091
giant_player_boss_version=307605:2733042
dregora_version=821596:4522805
variedcommodities_version=257777:4466956
crafttweaker_version=MC1120-Main:1.12-4.1.20.709
zs_version=4.1.20.709
content_creator_version=622862:4721604
xat_version=279900:5717039
srpmixins_version=1119777:7136391
backpacks_version=684624:4203074
spartanweaponry_version=278141:6839689
toolbelt_version=260262:3459767
qualitytools_version=264756:2732994
lycanitesmobs_version=224770:4170997